#!/usr/bin/env bash
# Complete macOS setup for childoLand (Spring Boot kindergarten app).
# Installs Homebrew, OpenJDK 17, Maven, and a Dockerised Postgres; writes the
# .env file; builds the fat jar. Idempotent: re-run safely.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

DB_NAME="${DB_NAME:-childoland}"
DB_USER="${DB_USER:-childoland}"
DB_PASS="${DB_PASS:-childoland}"
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"

# Seeded admin account (KindergartenApplication.run -> TeacherService.initAdmin)
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@childoland.local}"
ADMIN_PASS="${ADMIN_PASS:-admin}"

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!! \033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mXX \033[0m %s\n' "$*" >&2; exit 1; }

[[ "$(uname -s)" == "Darwin" ]] || die "This script targets macOS only."

# ---------------------------------------------------------------------------
# 1. Homebrew
# ---------------------------------------------------------------------------
if ! command -v brew >/dev/null 2>&1; then
  log "Installing Homebrew"
  NONINTERACTIVE=1 /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  fi
else
  log "Homebrew already installed: $(brew --version | head -1)"
fi

# ---------------------------------------------------------------------------
# 2. OpenJDK 17 (the project targets Java 17)
# ---------------------------------------------------------------------------
if ! /usr/libexec/java_home -v 17 >/dev/null 2>&1; then
  log "Installing openjdk@17"
  brew install openjdk@17
  JDK_LINK="/Library/Java/JavaVirtualMachines/openjdk-17.jdk"
  if [[ ! -e "$JDK_LINK" ]]; then
    BREW_PREFIX="$(brew --prefix)"
    sudo ln -sfn \
      "${BREW_PREFIX}/opt/openjdk@17/libexec/openjdk.jdk" \
      "$JDK_LINK"
  fi
else
  log "openjdk@17 already available: $(/usr/libexec/java_home -v 17)"
fi
export JAVA_HOME="$(/usr/libexec/java_home -v 17)"
log "JAVA_HOME=$JAVA_HOME"

# ---------------------------------------------------------------------------
# 3. Maven
# ---------------------------------------------------------------------------
if ! command -v mvn >/dev/null 2>&1; then
  log "Installing Maven"
  brew install maven
else
  log "Maven already installed: $(mvn -version | head -1)"
fi

# ---------------------------------------------------------------------------
# 4. Docker runtime
# ---------------------------------------------------------------------------
# We need a working `docker` CLI talking to a running daemon. Order of preference:
#   1) Anything already on PATH whose daemon is up (Docker Desktop, Rancher
#      Desktop, OrbStack, an existing Colima).
#   2) Otherwise install + start Colima (CLI-only, no GUI required).
ensure_docker() {
  if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
    log "Docker daemon already running: $(docker --version)"
    return
  fi

  # Daemon down — try Colima first (we can start it headless).
  if ! command -v colima >/dev/null 2>&1; then
    log "Installing Colima + docker CLI"
    brew install colima docker
  fi

  if ! docker info >/dev/null 2>&1; then
    log "Starting Colima"
    colima start
  fi

  docker info >/dev/null 2>&1 \
    || die "Docker daemon still unreachable. Start Docker Desktop / Rancher Desktop / OrbStack and re-run, or run 'colima start' manually."
}
ensure_docker

# docker compose (plugin) vs docker-compose (legacy)
if docker compose version >/dev/null 2>&1; then
  DC=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  DC=(docker-compose)
else
  log "Installing docker-compose plugin"
  brew install docker-compose
  DC=(docker compose)
fi

# ---------------------------------------------------------------------------
# 5. .env file (compose reads it; the app reads it via scripts/run.sh)
# ---------------------------------------------------------------------------
ENV_FILE="${PROJECT_DIR}/.env"
if [[ -f "$ENV_FILE" ]]; then
  log ".env already exists, leaving as-is"
else
  log "Writing .env"
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup-macos.sh
# Used by docker-compose.yml (POSTGRES_* vars) and scripts/run.sh (Spring vars).
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASS=${DB_PASS}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}

DB_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
DB_USERNAME=${DB_USER}

# Seed admin (read by TeacherService.initAdmin on first boot)
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASS=${ADMIN_PASS}
EOF
fi

# ---------------------------------------------------------------------------
# 6. Start Postgres container
# ---------------------------------------------------------------------------
log "Starting Postgres container (docker compose up -d)"
cd "$PROJECT_DIR"
"${DC[@]}" up -d postgres

log "Waiting for Postgres to be healthy"
for i in {1..60}; do
  status="$("${DC[@]}" ps --format '{{.Health}}' postgres 2>/dev/null | head -1)"
  [[ "$status" == "healthy" ]] && break
  # Older compose versions don't emit Health here; fall back to pg_isready inside the container.
  if "${DC[@]}" exec -T postgres pg_isready -U "$DB_USER" -d "$DB_NAME" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
"${DC[@]}" exec -T postgres pg_isready -U "$DB_USER" -d "$DB_NAME" >/dev/null 2>&1 \
  || die "Postgres container did not become ready."
log "Postgres is up on ${DB_HOST}:${DB_PORT}"

# ---------------------------------------------------------------------------
# 7. Build
# ---------------------------------------------------------------------------
log "Building the project (skipping tests)"
mvn -q -DskipTests package

JAR="$(ls -1 "${PROJECT_DIR}/target/"*.jar 2>/dev/null | grep -v '\.original$' | head -1)"
[[ -n "$JAR" ]] || die "Build produced no jar in target/."

log "Setup complete."
echo
echo "    Built artifact:    ${JAR}"
echo "    Run the app:       ./scripts/run.sh"
echo "    Stop Postgres:     docker compose down            (data persists)"
echo "    Reset Postgres:    docker compose down -v         (wipes the volume)"
echo "    psql into the DB:  docker compose exec postgres psql -U ${DB_USER} -d ${DB_NAME}"
echo
